### ISSUE TITLE
All summers become 2023

### ISSUE THREAD

**Issue by ianriley97** [KSU-CS-Software-Engineering/cs-student-portal#11]
When setting a summer, it always defaults to Summer of 2023. This should NOT be the behavior.

**Comment by ianriley97** [comment]
I have been told it's not summer of 2023, but rather the latest year + summer.

**Comment by filip-ksu** [comment]
In 81bc95441e8ac208263c7e41b38ba84c76b7ac2f changed so it becomes the summer nearest to the original semester term
